import { chromium } from '../_pw/node_modules/playwright/index.mjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const A = path.dirname(fileURLToPath(import.meta.url));
const BASE = 'http://localhost:8081';
const UD = '/tmp/ditl-pw-lane-a';
const CLASS = 'd1715000-0000-4000-a000-000000000301';
const S1 = '2bcee429-11ce-4f84-b2de-9aab349f03cc';
const PASS = process.env.DITL_TEACHER_PASS || 'DITL-teacher-test';
const exe = process.env.HOME + '/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
const browser = await chromium.launchPersistentContext(UD, { headless: true, viewport: { width: 1280, height: 900 }, executablePath: exe, args: ['--disable-dev-shm-usage','--no-first-run'] });
const p = browser.pages()[0] || (await browser.newPage());
await p.goto(`${BASE}/sign-in`); await p.waitForTimeout(400);
await p.evaluate(() => { try { localStorage.clear(); sessionStorage.clear(); } catch {} });
await p.goto(`${BASE}/sign-in`); await p.waitForTimeout(600);
await p.locator('input').nth(0).fill('ditl-teacher-a');
await p.locator('input[type=password]').first().fill(PASS);
await p.locator('input[type=password]').first().press('Enter');
await p.waitForTimeout(5000);
await p.goto(`${BASE}/class/${CLASS}/student/${S1}`); await p.waitForTimeout(2500);
const tab = p.getByRole('tab', { name: 'Details' });
console.log('tab count', await tab.count());
await tab.first().click();
await p.waitForTimeout(1500);
await p.screenshot({ path: path.join(A, 'probe2-details.png'), fullPage: true });
console.log((await p.innerText('body')).slice(0, 1500));
// try edit
const pref = p.getByText('Preferred name');
console.log('pref', await pref.count());
if (await pref.count()) await pref.first().click();
await p.waitForTimeout(1000);
console.log('inputs', await p.locator('input:visible').count());
console.log((await p.innerText('body')).slice(0, 800));
await browser.close();
