import { chromium } from './../_pw/node_modules/playwright/index.mjs';
const A = new URL('.', import.meta.url).pathname;
const teacherPw = 'DITL-teacher-test';
const b = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 } });
const p = await ctx.newPage();
await p.goto('http://localhost:8081/sign-in');
await p.waitForTimeout(1500);
await p.locator('input').nth(0).fill('ditl-teacher-a');
await p.locator('input[type=password]').first().fill(teacherPw);
await p.locator('input[type=password]').first().press('Enter');
await p.waitForTimeout(6000);
await p.goto('http://localhost:8081/messages/24afbe48-3bf7-49be-90da-88e09bcfe1c5');
await p.waitForTimeout(4000);
await p.screenshot({ path: A + 'r6-thread.png' });
const body = await p.innerText('body');
console.log('BODY', body.slice(0, 2000).replace(/\n+/g, ' | '));
const html = await p.content();
const hits = [...html.matchAll(/ditl-T-03-UI-01[^<\"']{0,80}/g)].map((m) => m[0]);
console.log('HTML_HITS', hits.slice(0, 10));
console.log('HAS_SICK', /sick|makeup|Period 3|make up/i.test(html + body));
console.log('PLACEHOLDERS', await p.locator('textarea, input[placeholder]').evaluateAll((els) => els.map((e) => ({ tag: e.tagName, ph: e.getAttribute('placeholder'), val: e.value?.slice?.(0, 40) }))));
// list bubble-like nodes
const bubbles = await p.locator('[class*="message"], [data-testid*="message"], [role="listitem"]').count().catch(() => -1);
console.log('bubble_countish', bubbles);
const allText = await p.evaluate(() => document.body.innerText);
console.log('FULL_LEN', allText.length);
console.log('FULL', allText.slice(0, 2500).replace(/\n+/g, ' || '));
await b.close();
