#!/usr/bin/env python3
"""Build full corpus-v2 and write MANIFEST.md + size report."""
from __future__ import annotations

import sys
from pathlib import Path

# allow running from _gen/
sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import ROOT, page_count_pdf
from gen_admin import generate_admin
from gen_homework import generate_homework
from gen_papers import generate_papers
from gen_quizzes import generate_pack
from gen_worksheets import generate_worksheets


def du_mb(path: Path) -> float:
    total = 0
    if path.is_file():
        return path.stat().st_size / (1024 * 1024)
    for p in path.rglob("*"):
        if p.is_file() and ".venv" not in p.parts and p.suffix != ".pyc":
            total += p.stat().st_size
    return total / (1024 * 1024)


def write_manifest():
    lines = [
        "# corpus-v2 MANIFEST",
        "",
        "Generated by `notes/qa-fixtures/corpus-v2/_gen/gen_all.py`.",
        "License: **CC0 1.0** synthetic originals for Kelyra QA.",
        "Handwriting on student pages is **simulated** (fonts/jitter/scratch-outs).",
        "",
        "## Grading packs (32 students each)",
        "",
        "| Pack | Flatbed pages | Key | Phone JPGs |",
        "|------|---------------|-----|------------|",
    ]
    for subj in ("math", "science", "history", "english"):
        d = ROOT / "grading" / f"{subj}-quiz-32"
        stack = d / "stack-flatbed.pdf"
        pages = page_count_pdf(stack) if stack.exists() else "?"
        phones = sorted((d / "stack-phone").glob("*.jpg")) if (d / "stack-phone").exists() else []
        lines.append(f"| `{subj}-quiz-32` | {pages} | answer-key.pdf | {len(phones)} |")
    lines += [
        "",
        "## Homework",
        "",
    ]
    for folder in ("math-hw-12", "english-hw-10"):
        d = ROOT / "homework" / folder
        pages = page_count_pdf(d / "stack-flatbed.pdf") if (d / "stack-flatbed.pdf").exists() else "?"
        lines.append(f"- `{folder}/` — stack pages: **{pages}** + answer-key.pdf")
    lines += [
        "",
        "## Worksheets",
        "- `worksheets/math-graph-assessment/` — graph interpretation + key",
        "- `worksheets/science-diagram-assessment/` — plant-cell labels + key",
        "",
        "## Papers",
        "- `papers/typed-research-sample.pdf`",
        "- `papers/handwritten-draft.pdf` + `handwritten-draft-phone.jpg`",
        "",
        "## Admin",
        "",
    ]
    admin = ROOT / "admin"
    for p in sorted(admin.glob("*.pdf")):
        lines.append(f"- `admin/{p.name}`")
    lines += [
        "",
        f"## Size",
        f"",
        f"- corpus-v2 total (excluding `_gen/.venv`): **{du_mb(ROOT):.1f} MB**",
        "",
        "## Regenerate",
        "",
        "```bash",
        "cd notes/qa-fixtures/corpus-v2/_gen",
        "python3 -m venv .venv && .venv/bin/pip install -r requirements.txt",
        ".venv/bin/python gen_all.py",
        "```",
        "",
    ]
    (ROOT / "MANIFEST.md").write_text("\n".join(lines) + "\n")
    print("wrote MANIFEST.md")


def write_readme():
    text = """# Kelyra QA Fixture Corpus v2

Comprehensive **synthetic / CC0** test artifacts for batch scan → split → gradebook,
capture, KEYGRADE, and admin/forms ingest. Built for card `t_ac2790bc`.

## Quick map

| Path | Use |
|------|-----|
| `grading/*-quiz-32/` | 32-page flatbed stacks + answer keys + phone JPG samples + roster/meta |
| `homework/` | Smaller graded HW packs (math, english) |
| `worksheets/` | Graph / diagram assessment sheets + keys |
| `papers/` | Typed research sample + simulated handwritten draft |
| `admin/` | Enrollment, parent info, roster, syllabi, lesson plan, rubric, curricula |
| `_gen/` | Python generators (reportlab + Pillow) — regenerate anytime |

## How to use with Kelyra flows

1. **Batch ingest / class stack:** upload `grading/<subject>-quiz-32/stack-flatbed.pdf` (32 pages).
2. **Answer key:** upload companion `answer-key.pdf` for KEYGRADE / Needs review.
3. **Phone capture:** use files under `stack-phone/` (perspective + compression simulated).
4. **Roster match:** `roster.json` lists 32 synthetic students (Alex Rivera style).
5. **Admin OCR / forms:** try PDFs under `admin/`.
6. **Do not** treat names or handwriting as real — `meta.json` marks `handwriting: simulated`.

## License / privacy

- Original synthetic content, dedicated to **CC0 1.0**.
- No copyrighted textbook/worksheet scrapes.
- No real student PII or photos of minors.

## Related

- Inventory: `../CORPUS-INVENTORY-2026-09-24.md`
- Older DITL single-page fixtures: `../ditl/` (kept; not replaced)
- Batch edge-case PDFs: `../batch-ingest/`
"""
    (ROOT / "README.md").write_text(text)


def main():
    print("Building corpus-v2 …")
    for subj in ("math", "science", "history", "english"):
        generate_pack(subj)
    generate_homework()
    generate_worksheets()
    generate_papers()
    generate_admin()
    write_readme()
    write_manifest()
    print(f"DONE · total ≈ {du_mb(ROOT):.1f} MB")


if __name__ == "__main__":
    main()
