/* Generated by scripts/build-icons.mjs — do not edit by hand. */
import type { ImageSourcePropType } from 'react-native';

import menu from '../../../assets/icons/menu.png';
import filter from '../../../assets/icons/filter.png';
import close from '../../../assets/icons/close.png';
import setup from '../../../assets/icons/setup.png';
import today from '../../../assets/icons/today.png';
import capture from '../../../assets/icons/capture.png';
import records from '../../../assets/icons/records.png';
import classes from '../../../assets/icons/classes.png';
import family from '../../../assets/icons/family.png';
import inbox from '../../../assets/icons/inbox.png';
import zoomIn from '../../../assets/icons/zoomIn.png';
import zoomOut from '../../../assets/icons/zoomOut.png';
import search from '../../../assets/icons/search.png';
import bell from '../../../assets/icons/bell.png';
import ask from '../../../assets/icons/ask.png';
import person from '../../../assets/icons/person.png';
import parents from '../../../assets/icons/parents.png';
import children from '../../../assets/icons/children.png';
import back from '../../../assets/icons/back.png';
import send from '../../../assets/icons/send.png';
import check from '../../../assets/icons/check.png';
import mail from '../../../assets/icons/mail.png';
import chat from '../../../assets/icons/chat.png';
import settings from '../../../assets/icons/settings.png';
import share from '../../../assets/icons/share.png';
import save from '../../../assets/icons/save.png';
import compose from '../../../assets/icons/compose.png';
import plus from '../../../assets/icons/plus.png';
import mic from '../../../assets/icons/mic.png';
import focus from '../../../assets/icons/focus.png';
import login from '../../../assets/icons/login.png';
import history from '../../../assets/icons/history.png';
import work from '../../../assets/icons/work.png';
import practice from '../../../assets/icons/practice.png';
import details from '../../../assets/icons/details.png';
import manage from '../../../assets/icons/manage.png';
import photo from '../../../assets/icons/photo.png';
import file from '../../../assets/icons/file.png';
import link from '../../../assets/icons/link.png';
import post from '../../../assets/icons/post.png';
import alert from '../../../assets/icons/alert.png';
import speaker from '../../../assets/icons/speaker.png';
import mute from '../../../assets/icons/mute.png';
import grades from '../../../assets/icons/grades.png';
import statusAssigned from '../../../assets/icons/statusAssigned.png';
import statusStarted from '../../../assets/icons/statusStarted.png';
import statusCompleted from '../../../assets/icons/statusCompleted.png';
import statusGraded from '../../../assets/icons/statusGraded.png';
import termAll from '../../../assets/icons/termAll.png';
import termQ1 from '../../../assets/icons/termQ1.png';
import termQ2 from '../../../assets/icons/termQ2.png';
import termQ3 from '../../../assets/icons/termQ3.png';
import termQ4 from '../../../assets/icons/termQ4.png';
import termS1 from '../../../assets/icons/termS1.png';
import termS2 from '../../../assets/icons/termS2.png';
import termYear from '../../../assets/icons/termYear.png';
import feedSchool from '../../../assets/icons/feedSchool.png';
import feedClass from '../../../assets/icons/feedClass.png';
import feedBook from '../../../assets/icons/feedBook.png';
import feedEnglish from '../../../assets/icons/feedEnglish.png';
import feedLanguage from '../../../assets/icons/feedLanguage.png';
import feedPencil from '../../../assets/icons/feedPencil.png';
import feedMath from '../../../assets/icons/feedMath.png';
import feedGeom from '../../../assets/icons/feedGeom.png';
import feedStat from '../../../assets/icons/feedStat.png';
import feedScience from '../../../assets/icons/feedScience.png';
import feedChem from '../../../assets/icons/feedChem.png';
import feedPhysics from '../../../assets/icons/feedPhysics.png';
import feedBio from '../../../assets/icons/feedBio.png';
import feedLab from '../../../assets/icons/feedLab.png';
import feedGlobe from '../../../assets/icons/feedGlobe.png';
import feedWorldHistory from '../../../assets/icons/feedWorldHistory.png';
import feedUSHistory from '../../../assets/icons/feedUSHistory.png';
import feedStateHistory from '../../../assets/icons/feedStateHistory.png';
import feedMap from '../../../assets/icons/feedMap.png';
import feedGov from '../../../assets/icons/feedGov.png';
import feedEcon from '../../../assets/icons/feedEcon.png';
import feedBible from '../../../assets/icons/feedBible.png';
import feedArt from '../../../assets/icons/feedArt.png';
import feedMusic from '../../../assets/icons/feedMusic.png';
import feedTheater from '../../../assets/icons/feedTheater.png';
import feedSport from '../../../assets/icons/feedSport.png';
import feedCode from '../../../assets/icons/feedCode.png';
import feedRobot from '../../../assets/icons/feedRobot.png';
import feedShop from '../../../assets/icons/feedShop.png';
import feedAg from '../../../assets/icons/feedAg.png';
import feedHealth from '../../../assets/icons/feedHealth.png';
import feedNews from '../../../assets/icons/feedNews.png';
import feedLibrary from '../../../assets/icons/feedLibrary.png';
import feedHeart from '../../../assets/icons/feedHeart.png';
import feedStar from '../../../assets/icons/feedStar.png';
import feedSun from '../../../assets/icons/feedSun.png';

export const ICON_ASSETS: Record<string, ImageSourcePropType> = {
  'menu': menu,
  'filter': filter,
  'close': close,
  'setup': setup,
  'today': today,
  'capture': capture,
  'records': records,
  'classes': classes,
  'family': family,
  'inbox': inbox,
  'zoomIn': zoomIn,
  'zoomOut': zoomOut,
  'search': search,
  'bell': bell,
  'ask': ask,
  'person': person,
  'parents': parents,
  'children': children,
  'back': back,
  'send': send,
  'check': check,
  'mail': mail,
  'chat': chat,
  'settings': settings,
  'share': share,
  'save': save,
  'compose': compose,
  'plus': plus,
  'mic': mic,
  'focus': focus,
  'login': login,
  'history': history,
  'work': work,
  'practice': practice,
  'details': details,
  'manage': manage,
  'photo': photo,
  'file': file,
  'link': link,
  'post': post,
  'alert': alert,
  'speaker': speaker,
  'mute': mute,
  'grades': grades,
  'statusAssigned': statusAssigned,
  'statusStarted': statusStarted,
  'statusCompleted': statusCompleted,
  'statusGraded': statusGraded,
  'termAll': termAll,
  'termQ1': termQ1,
  'termQ2': termQ2,
  'termQ3': termQ3,
  'termQ4': termQ4,
  'termS1': termS1,
  'termS2': termS2,
  'termYear': termYear,
  'feedSchool': feedSchool,
  'feedClass': feedClass,
  'feedBook': feedBook,
  'feedEnglish': feedEnglish,
  'feedLanguage': feedLanguage,
  'feedPencil': feedPencil,
  'feedMath': feedMath,
  'feedGeom': feedGeom,
  'feedStat': feedStat,
  'feedScience': feedScience,
  'feedChem': feedChem,
  'feedPhysics': feedPhysics,
  'feedBio': feedBio,
  'feedLab': feedLab,
  'feedGlobe': feedGlobe,
  'feedWorldHistory': feedWorldHistory,
  'feedUSHistory': feedUSHistory,
  'feedStateHistory': feedStateHistory,
  'feedMap': feedMap,
  'feedGov': feedGov,
  'feedEcon': feedEcon,
  'feedBible': feedBible,
  'feedArt': feedArt,
  'feedMusic': feedMusic,
  'feedTheater': feedTheater,
  'feedSport': feedSport,
  'feedCode': feedCode,
  'feedRobot': feedRobot,
  'feedShop': feedShop,
  'feedAg': feedAg,
  'feedHealth': feedHealth,
  'feedNews': feedNews,
  'feedLibrary': feedLibrary,
  'feedHeart': feedHeart,
  'feedStar': feedStar,
  'feedSun': feedSun,
};
